services:
    Linkin\Bundle\SwaggerResolverBundle\Builder\SwaggerResolverBuilder:
        arguments:
            - []
    linkin_swagger_resolver.builder:
        alias: Linkin\Bundle\SwaggerResolverBundle\Builder\SwaggerResolverBuilder

    linkin_swagger_resolver.loader.configuration:
        class:      Linkin\Bundle\SwaggerResolverBundle\Loader\NelmioApiDocConfigurationLoader
        public:     false
        arguments:
            - '@nelmio_api_doc.generator'

    linkin_swagger_resolver.validator.array.max_items:
        class:      Linkin\Bundle\SwaggerResolverBundle\Validator\ArrayMaxItemsValidator
        public:     false
        tags:
            - { name: linkin_swagger_resolver.validator }

    linkin_swagger_resolver.validator.array.min_items:
        class:      Linkin\Bundle\SwaggerResolverBundle\Validator\ArrayMinItemsValidator
        public:     false
        tags:
            - { name: linkin_swagger_resolver.validator }

    linkin_swagger_resolver.validator.array.unique_items:
        class:      Linkin\Bundle\SwaggerResolverBundle\Validator\ArrayUniqueItemsValidator
        public:     false
        tags:
            - { name: linkin_swagger_resolver.validator }

    linkin_swagger_resolver.validator.format.date:
        class:      Linkin\Bundle\SwaggerResolverBundle\Validator\FormatDateValidator
        public:     false
        tags:
            - { name: linkin_swagger_resolver.validator }

    linkin_swagger_resolver.validator.format.date_time:
        class:      Linkin\Bundle\SwaggerResolverBundle\Validator\FormatDateTimeValidator
        public:     false
        tags:
            - { name: linkin_swagger_resolver.validator }

    linkin_swagger_resolver.validator.format.timestamp:
        class:      Linkin\Bundle\SwaggerResolverBundle\Validator\FormatTimestampValidator
        public:     false
        tags:
            - { name: linkin_swagger_resolver.validator }

    linkin_swagger_resolver.validator.format.time:
        class:      Linkin\Bundle\SwaggerResolverBundle\Validator\FormatTimeValidator
        public:     false
        tags:
            - { name: linkin_swagger_resolver.validator }

    linkin_swagger_resolver.validator.number.maximum:
        class:      Linkin\Bundle\SwaggerResolverBundle\Validator\NumberMaximumValidator
        public:     false
        tags:
            - { name: linkin_swagger_resolver.validator }

    linkin_swagger_resolver.validator.number.minimum:
        class:      Linkin\Bundle\SwaggerResolverBundle\Validator\NumberMinimumValidator
        public:     false
        tags:
            - { name: linkin_swagger_resolver.validator }

    linkin_swagger_resolver.validator.number.multiple_of:
        class:      Linkin\Bundle\SwaggerResolverBundle\Validator\NumberMultipleOfValidator
        public:     false
        tags:
            - { name: linkin_swagger_resolver.validator }

    linkin_swagger_resolver.validator.string.max_length:
        class:      Linkin\Bundle\SwaggerResolverBundle\Validator\StringMaxLengthValidator
        public:     false
        tags:
            - { name: linkin_swagger_resolver.validator }

    linkin_swagger_resolver.validator.string.min_length:
        class:      Linkin\Bundle\SwaggerResolverBundle\Validator\StringMinLengthValidator
        public:     false
        tags:
            - { name: linkin_swagger_resolver.validator }

    linkin_swagger_resolver.validator.string.pattern:
        class:      Linkin\Bundle\SwaggerResolverBundle\Validator\StringPatternValidator
        public:     false
        tags:
            - { name: linkin_swagger_resolver.validator }
