services:
    Linkin\Bundle\SwaggerResolverBundle\Builder\SwaggerResolverBuilder:
        arguments:
            - [] # validators
            - [] # normalizers
            - '%linkin_swagger_resolver.enable_normalization%'

    Linkin\Bundle\SwaggerResolverBundle\Configuration\SwaggerConfiguration:
        arguments:
            - '@Linkin\Bundle\SwaggerResolverBundle\Merger\PathParameterMerger'
            - '@Linkin\Bundle\SwaggerResolverBundle\Loader\SwaggerConfigurationLoaderInterface'

    Linkin\Bundle\SwaggerResolverBundle\Factory\SwaggerResolverFactory:
        public: true
        arguments:
            - '@Linkin\Bundle\SwaggerResolverBundle\Builder\SwaggerResolverBuilder'
            - '@Linkin\Bundle\SwaggerResolverBundle\Configuration\SwaggerConfiguration'
            - '@router'
    linkin_swagger_resolver.factory:
        alias: Linkin\Bundle\SwaggerResolverBundle\Factory\SwaggerResolverFactory

    Linkin\Bundle\SwaggerResolverBundle\Merger\PathParameterMerger:
        arguments:
            - '@Linkin\Bundle\SwaggerResolverBundle\Merger\MergeStrategyInterface'

    Linkin\Bundle\SwaggerResolverBundle\Merger\MergeStrategyInterface:
        alias: '@Linkin\Bundle\SwaggerResolverBundle\Merger\Strategy\StrictMergeStrategy'

    Linkin\Bundle\SwaggerResolverBundle\Merger\Strategy\CombineNameMergeStrategy: ~
    Linkin\Bundle\SwaggerResolverBundle\Merger\Strategy\ReplaceFirstWinMergeStrategy: ~
    Linkin\Bundle\SwaggerResolverBundle\Merger\Strategy\ReplaceLastWinMergeStrategy: ~
    Linkin\Bundle\SwaggerResolverBundle\Merger\Strategy\StrictMergeStrategy: ~

    Linkin\Bundle\SwaggerResolverBundle\Normalizer\BooleanNormalizer:
        tags:
            - { name: linkin_swagger_resolver.normalizer }
    Linkin\Bundle\SwaggerResolverBundle\Normalizer\IntegerNormalizer:
        tags:
            - { name: linkin_swagger_resolver.normalizer }
    Linkin\Bundle\SwaggerResolverBundle\Normalizer\NumberNormalizer:
        tags:
            - { name: linkin_swagger_resolver.normalizer }

    Linkin\Bundle\SwaggerResolverBundle\Validator\ArrayMaxItemsValidator:
        tags:
            - { name: linkin_swagger_resolver.validator }
    Linkin\Bundle\SwaggerResolverBundle\Validator\ArrayMinItemsValidator:
        tags:
            - { name: linkin_swagger_resolver.validator }
    Linkin\Bundle\SwaggerResolverBundle\Validator\ArrayUniqueItemsValidator:
        tags:
            - { name: linkin_swagger_resolver.validator }
    Linkin\Bundle\SwaggerResolverBundle\Validator\FormatDateValidator:
        tags:
            - { name: linkin_swagger_resolver.validator }
    Linkin\Bundle\SwaggerResolverBundle\Validator\FormatDateTimeValidator:
        tags:
            - { name: linkin_swagger_resolver.validator }
    Linkin\Bundle\SwaggerResolverBundle\Validator\FormatTimestampValidator:
        tags:
            - { name: linkin_swagger_resolver.validator }
    Linkin\Bundle\SwaggerResolverBundle\Validator\FormatTimeValidator:
        tags:
            - { name: linkin_swagger_resolver.validator }
    Linkin\Bundle\SwaggerResolverBundle\Validator\NumberMaximumValidator:
        tags:
            - { name: linkin_swagger_resolver.validator }
    Linkin\Bundle\SwaggerResolverBundle\Validator\NumberMinimumValidator:
        tags:
            - { name: linkin_swagger_resolver.validator }
    Linkin\Bundle\SwaggerResolverBundle\Validator\NumberMultipleOfValidator:
        tags:
            - { name: linkin_swagger_resolver.validator }
    Linkin\Bundle\SwaggerResolverBundle\Validator\StringMaxLengthValidator:
        tags:
            - { name: linkin_swagger_resolver.validator }
    Linkin\Bundle\SwaggerResolverBundle\Validator\StringMinLengthValidator:
        tags:
            - { name: linkin_swagger_resolver.validator }
    Linkin\Bundle\SwaggerResolverBundle\Validator\StringPatternValidator:
        tags:
            - { name: linkin_swagger_resolver.validator }
